"""
SQL 代码封装器 - 将 SQL 封装成 Python/Java 数据库操作代码
用于在 OpenClaw 沙箱中安全执行
"""

import json
from typing import Dict, Any, Optional, List
from dataclasses import dataclass
from enum import Enum


class CodeLanguage(Enum):
    """支持的代码语言"""
    PYTHON = "python"
    JAVA = "java"


@dataclass
class CodeWrapperConfig:
    """代码封装配置"""
    language: CodeLanguage = CodeLanguage.PYTHON
    database_type: str = "sqlite"  # sqlite, mysql, postgresql
    include_result_formatting: bool = True
    include_error_handling: bool = True
    max_result_rows: int = 1000


class SQLCodeWrapper:
    """
    SQL 代码封装器
    
    将 Text2SQL 生成的 SQL 语句封装成可执行的 Python/Java 代码，
    用于在 OpenClaw 沙箱中安全执行。
    """
    
    def __init__(self, config: CodeWrapperConfig = None):
        self.config = config or CodeWrapperConfig()
        print(f"[SQL_CODE_WRAPPER] 初始化代码封装器，语言: {self.config.language.value}")
    
    def wrap_sql(self, sql: str, db_config: Dict[str, Any] = None) -> Dict[str, Any]:
        """
        将 SQL 封装成可执行代码
        
        Args:
            sql: SQL 语句
            db_config: 数据库配置（路径或连接信息）
            
        Returns:
            Dict: 包含生成的代码和元数据
        """
        if self.config.language == CodeLanguage.PYTHON:
            return self._wrap_python(sql, db_config)
        elif self.config.language == CodeLanguage.JAVA:
            return self._wrap_java(sql, db_config)
        else:
            return {
                'success': False,
                'error': f'不支持的语言: {self.config.language}'
            }
    
    def _wrap_python(self, sql: str, db_config: Dict[str, Any] = None) -> Dict[str, Any]:
        """
        封装成 Python 代码
        
        生成可直接执行的 Python 脚本，使用标准库 sqlite3 或第三方库连接数据库
        """
        db_path = db_config.get('path', 'instance/badcase_doctor.db') if db_config else 'instance/badcase_doctor.db'
        db_type = db_config.get('type', self.config.database_type) if db_config else self.config.database_type
        
        # 构建 Python 代码
        code_lines = [
            "# Auto-generated Python code for SQL execution",
            "# Generated by BadCase Doctor Text2SQL Code Wrapper",
            "",
            "import json",
            "import sys",
        ]
        
        # 根据数据库类型导入不同模块
        if db_type == 'sqlite':
            code_lines.append("import sqlite3")
        elif db_type in ['mysql', 'postgresql']:
            code_lines.append("try:")
            code_lines.append("    import pymysql" if db_type == 'mysql' else "    import psycopg2")
            code_lines.append("except ImportError:")
            code_lines.append("    print(json.dumps({'success': False, 'error': '数据库驱动未安装'}))")
            code_lines.append("    sys.exit(1)")
        
        code_lines.extend([
            "",
            "",
            "def execute_sql():",
            "    \"\"\"执行 SQL 查询并返回结果\"\"\"",
            "    result = {",
            "        'success': False,",
            "        'data': [],",
            "        'columns': [],",
            "        'row_count': 0,",
            "        'error': None",
            "    }",
            "    ",
            "    try:",
        ])
        
        # 数据库连接代码
        if db_type == 'sqlite':
            code_lines.extend([
                f"        conn = sqlite3.connect('{db_path}')",
                "        conn.row_factory = sqlite3.Row",
                "        cursor = conn.cursor()",
            ])
        elif db_type == 'mysql':
            host = db_config.get('host', 'localhost')
            port = db_config.get('port', 3306)
            user = db_config.get('user', 'root')
            password = db_config.get('password', '')
            database = db_config.get('database', 'badcase_doctor')
            code_lines.extend([
                f"        conn = pymysql.connect(",
                f"            host='{host}',",
                f"            port={port},",
                f"            user='{user}',",
                f"            password='{password}',",
                f"            database='{database}'",
                "        )",
                "        cursor = conn.cursor(pymysql.cursors.DictCursor)",
            ])
        
        # SQL 执行代码
        code_lines.extend([
            "        ",
            f"        sql = \"\"\"{sql}\"\"\"",
            "        cursor.execute(sql)",
            "        ",
            "        if sql.strip().upper().startswith('SELECT'):",
            "            rows = cursor.fetchall()",
            f"            # 限制结果数量（最多 {self.config.max_result_rows} 行）",
            f"            rows = rows[: {self.config.max_result_rows}]",
            "            ",
            "            # 转换为字典列表",
            "            if hasattr(rows[0], 'keys') if rows else True:",
            "                data = [dict(row) for row in rows]",
            "            else:",
            "                columns = [desc[0] for desc in cursor.description] if cursor.description else []",
            "                data = [dict(zip(columns, row)) for row in rows]",
            "            ",
            "            result['data'] = data",
            "            result['columns'] = list(data[0].keys()) if data else []",
            "            result['row_count'] = len(data)",
            "        else:",
            "            conn.commit()",
            "            result['row_count'] = cursor.rowcount",
            "        ",
            "        result['success'] = True",
            "        ",
            "    except Exception as e:",
            "        result['error'] = str(e)",
            "    finally:",
            "        try:",
            "            if 'conn' in locals():",
            "                conn.close()",
            "        except:",
            "            pass",
            "    ",
            "    return result",
            "",
            "",
            "if __name__ == '__main__':",
            "    result = execute_sql()",
            "    print(json.dumps(result, ensure_ascii=False, default=str))",
        ])
        
        code = "\n".join(code_lines)
        
        return {
            'success': True,
            'code': code,
            'language': 'python',
            'sql': sql,
            'db_type': db_type,
            'executable': True,
            'run_command': f"python -c \"{code.replace(chr(34), chr(92)+chr(34)).replace(chr(10), chr(92)+chr(110))}\""
        }
    
    def _wrap_java(self, sql: str, db_config: Dict[str, Any] = None) -> Dict[str, Any]:
        """
        封装成 Java 代码
        
        生成可直接执行的 Java 类，使用 JDBC 连接数据库
        """
        db_path = db_config.get('path', 'instance/badcase_doctor.db') if db_config else 'instance/badcase_doctor.db'
        db_type = db_config.get('type', self.config.database_type) if db_config else self.config.database_type
        
        # JDBC 配置
        if db_type == 'sqlite':
            jdbc_driver = "org.sqlite.JDBC"
            jdbc_url = f"jdbc:sqlite:{db_path}"
        elif db_type == 'mysql':
            host = db_config.get('host', 'localhost')
            port = db_config.get('port', 3306)
            database = db_config.get('database', 'badcase_doctor')
            jdbc_driver = "com.mysql.cj.jdbc.Driver"
            jdbc_url = f"jdbc:mysql://{host}:{port}/{database}"
        else:
            jdbc_driver = "org.postgresql.Driver"
            jdbc_url = f"jdbc:postgresql://localhost:5432/badcase_doctor"
        
        # 构建 Java 代码
        code = f'''// Auto-generated Java code for SQL execution
// Generated by BadCase Doctor Text2SQL Code Wrapper

import java.sql.*;
import java.util.*;
import com.google.gson.Gson;

public class SQLExecutor {{
    
    public static void main(String[] args) {{
        String jdbcDriver = "{jdbc_driver}";
        String jdbcUrl = "{jdbc_url}";
        String username = args.length > 0 ? args[0] : "";
        String password = args.length > 1 ? args[1] : "";
        
        Map<String, Object> result = new HashMap<>();
        result.put("success", false);
        result.put("data", new ArrayList<>());
        result.put("columns", new ArrayList<>());
        result.put("row_count", 0);
        result.put("error", null);
        
        Connection conn = null;
        try {{
            Class.forName(jdbcDriver);
            conn = DriverManager.getConnection(jdbcUrl, username, password);
            
            String sql = """{sql}""";
            Statement stmt = conn.createStatement();
            
            if (sql.trim().toUpperCase().startsWith("SELECT")) {{
                ResultSet rs = stmt.executeQuery(sql);
                ResultSetMetaData metaData = rs.getMetaData();
                int columnCount = metaData.getColumnCount();
                
                List<String> columns = new ArrayList<>();
                for (int i = 1; i <= columnCount; i++) {{
                    columns.add(metaData.getColumnName(i));
                }}
                result.put("columns", columns);
                
                List<Map<String, Object>> data = new ArrayList<>();
                int rowCount = 0;
                while (rs.next() && rowCount < {self.config.max_result_rows}) {{
                    Map<String, Object> row = new HashMap<>();
                    for (int i = 1; i <= columnCount; i++) {{
                        row.put(metaData.getColumnName(i), rs.getObject(i));
                    }}
                    data.add(row);
                    rowCount++;
                }}
                
                result.put("data", data);
                result.put("row_count", rowCount);
            }} else {{
                int affectedRows = stmt.executeUpdate(sql);
                result.put("row_count", affectedRows);
            }}
            
            result.put("success", true);
            
        }} catch (Exception e) {{
            result.put("error", e.getMessage());
        }} finally {{
            try {{
                if (conn != null) conn.close();
            }} catch (SQLException e) {{
                // ignore
            }}
        }}
        
        System.out.println(new Gson().toJson(result));
    }}
}}
'''
        
        return {
            'success': True,
            'code': code,
            'language': 'java',
            'sql': sql,
            'db_type': db_type,
            'executable': True,
            'compile_command': f'javac -cp ".:gson.jar:sqlite-jdbc.jar" SQLExecutor.java',
            'run_command': f'java -cp ".:gson.jar:sqlite-jdbc.jar" SQLExecutor'
        }
    
    def wrap_batch(self, sql_list: List[str], db_config: Dict[str, Any] = None) -> Dict[str, Any]:
        """
        批量封装多个 SQL 语句
        
        Args:
            sql_list: SQL 语句列表
            db_config: 数据库配置
            
        Returns:
            Dict: 包含批量执行代码
        """
        if self.config.language == CodeLanguage.PYTHON:
            return self._wrap_batch_python(sql_list, db_config)
        else:
            # Java 不支持批量脚本，逐个封装
            results = []
            for sql in sql_list:
                results.append(self._wrap_java(sql, db_config))
            return {
                'success': True,
                'results': results,
                'language': self.config.language.value
            }
    
    def _wrap_batch_python(self, sql_list: List[str], db_config: Dict[str, Any] = None) -> Dict[str, Any]:
        """批量封装 Python 代码"""
        db_path = db_config.get('path', 'instance/badcase_doctor.db') if db_config else 'instance/badcase_doctor.db'
        
        # 构建 SQL 列表的 JSON 字符串
        sql_json = json.dumps(sql_list, ensure_ascii=False)
        
        code = f'''# Auto-generated Python code for batch SQL execution
import json
import sqlite3

def execute_batch():
    sql_list = {sql_json}
    db_path = "{db_path}"
    results = []
    
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()
    
    for sql in sql_list:
        result = {{
            'sql': sql,
            'success': False,
            'data': [],
            'error': None
        }}
        try:
            cursor.execute(sql)
            if sql.strip().upper().startswith('SELECT'):
                rows = cursor.fetchall()
                result['data'] = [dict(row) for row in rows]
                result['row_count'] = len(rows)
            else:
                conn.commit()
                result['row_count'] = cursor.rowcount
            result['success'] = True
        except Exception as e:
            result['error'] = str(e)
        results.append(result)
    
    conn.close()
    return results

if __name__ == '__main__':
    results = execute_batch()
    print(json.dumps(results, ensure_ascii=False, default=str))
'''
        
        return {
            'success': True,
            'code': code,
            'language': 'python',
            'sql_count': len(sql_list),
            'executable': True
        }
    
    def generate_test_code(self, sql: str, test_data: Dict[str, Any] = None) -> Dict[str, Any]:
        """
        生成测试代码（用于验证 SQL 正确性）
        
        Args:
            sql: SQL 语句
            test_data: 测试数据（可选）
            
        Returns:
            Dict: 包含测试代码
        """
        base_result = self._wrap_python(sql, {'path': ':memory:'})  # 使用内存数据库
        
        test_code = base_result['code'].replace(
            "# Auto-generated Python code for SQL execution",
            """# Auto-generated Python TEST code for SQL validation
import unittest
"""
        )
        
        # 添加测试框架
        test_code += '''

class TestSQLExecution(unittest.TestCase):
    def test_sql_syntax(self):
        """测试 SQL 语法正确性"""
        result = execute_sql()
        self.assertIsNotNone(result)
        self.assertIn('success', result)
        
    def test_sql_returns_data(self):
        """测试 SQL 返回数据"""
        result = execute_sql()
        if result['success'] and result.get('data'):
            self.assertIsInstance(result['data'], list)

if __name__ == '__main__':
    unittest.main()
'''
        
        return {
            'success': True,
            'code': test_code,
            'language': 'python',
            'test_type': 'unittest'
        }


# 全局实例
sql_code_wrapper = None

def get_sql_code_wrapper(config: CodeWrapperConfig = None):
    """获取全局代码封装器实例"""
    global sql_code_wrapper
    if sql_code_wrapper is None:
        sql_code_wrapper = SQLCodeWrapper(config)
    return sql_code_wrapper
